#!/usr/bin/env bash
# Adds custom header to NGINX configuration file

sudo apt-get update
sudo apt-get -y install nginx

# Add custom header
sudo sed -i "/http {/a\		add_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf

sudo service nginx restart
