#!/usr/bin/env bash
# Pushes a file from client to server
# Accepts four parameters: path to file, remote username, server IP,
# path to private key
# scp command transfers file to the user's home directory
# Strict host key checking is disabled with scp

if [ $# -lt 4 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~
fi
