#!/usr/bin/env bash
# Installs and configures HAProxy load balancer to manage two web servers

# Update packages list
sudo apt-get -y update

# Install required packages
sudo apt-get -y install software-properties-common

# Add HAproxy repo and install HAProxy
sudo add-apt repository -y ppa:vbernat/haproxy-2.0
sudo apt-get -y update
sudo apt-get -y install haproxy

# HAProxy front and backend custom configurations
balancer="\
frontend haproxy_balancer
     bind *:80
     mode http
     default_backend web_servers

backend web_servers
     balance roundrobin
     server 321276-web-01 18.204.11.66:80 check
     server 321276-web-02 18.206.206.153:80 check
"
# Add custom configurations to haproxy.cfg file and create backup
sudo cp -a /etc/haproxy/haproxy.cfg{,.original}
echo "$balancer" >> /etc/haproxy/haproxy.cfg

# Activate HAProxy server
sudo service haproxy start
