#!/usr/bin/env bash
# Configures an Nginx web server to listen for requests on port 80.

rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
