#!/usr/bin/env bash
# Configures an NGINX web server to listen to requests on port 80.
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
kill "$(pgrep 'nginx' | head -1)"
