#!/usr/bin/env bash
#Displays the contents of the /etc/passwd file
#Displays only the username, ID, and Home directory fields

while read -r passwd; do
	echo "$passwd" | cut -d ":" -f1,3,6
done < "/etc/passwd"
