#!/usr/bin/env bash
#Modifies localhost's and facebook.com's IPs
#to new IPs

cp /etc/hosts ~/hosts.new
echo "127.0.0.2	localhost" > ~/hosts.new
echo "8.8.8.8	facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
